name: ios-commit-snapshots

on:
  issue_comment:
  types:
    - created

jobs:
  take-snapshots:
    if: (github.event.issue.pull_request != null) && github.event.comment.body == '!github take-ios-snapshots'
    name: "iOS Take and Commit Snapshots"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_12.4.app'
      - name: Show Xcode Version
        run: xcodebuild -version
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: "ios-framework:createXCFramework"
          dependencies-cache-key: |
            **/*.gradle
            **/*.gradle.kts
            buildSrc/src/**/*.kt
            **/gradle.properties
            gradle/**
      - name Generate Strings & Colors & Assets
        working-directory: ./ios
        run: make run-swiftgen
      - name: Take Snapshots
        working-directory: ./ios
        run: make take-snapshots
      - name: Commit new Snapshots
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"

          git commit -am "Update iOS Snapshots"
          git push
